name: Bearer

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
permissions:
  contents: read

jobs:
  rule_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bearer
        uses: bearer/bearer-action@v2
        with:
          format: sarif
          output: resultsBearer.sarif
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: resultsBearer.sarif
