name: Bearer

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
permissions:
  contents: read
  security-events: write

jobs:
  rule_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Bearer
        run: |
          wget https://github.com/Bearer/bearer/releases/download/v1.49.0/bearer_1.49.0_linux-amd64.deb 
          sudo dpkg -i bearer_1.49.0_linux-amd64.deb

      - name: Start Bearer
        run: |
          bearer scan . --format sarif --output resultsBearer.sarif
          
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: resultsBearer.sarif
