name: Semgrep Scan and Upload to DefectDojo

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:1.78.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: | 
          semgrep \
            --json \
            --output semgrep-results.json \
            --metrics=off \
            --config="p/default"

      - name: Save raw report
        uses: actions/upload-artifact@v4
        with:
          name: raw_report
          path: semgrep-results.json

      - name: Check and Create Product Type in DefectDojo
        env:
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          ORG_NAME: "SemmTest" # Название "организации" (типа продукта)
        run: |
          echo "Checking if product type '${ORG_NAME}' exists in DefectDojo..."

          RESPONSE=$(curl -s -X GET "${DEFECTDOJO_URL}/api/v2/product_types/" \
            -H "Authorization: Token ${DEFECTDOJO_API_KEY}")

          if ! echo "$RESPONSE" | jq empty > /dev/null 2>&1; then
            echo "Error: API did not return valid JSON. Response:"
            echo "$RESPONSE"
            exit 1
          fi

          PRODUCT_TYPE_ID=$(echo "$RESPONSE" | jq -r --arg NAME "$ORG_NAME" '.results[] | select(.name == $NAME) | .id')

          if [ -z "$PRODUCT_TYPE_ID" ]; then
            echo "Product type '${ORG_NAME}' does not exist. Creating it..."

            CREATE_RESPONSE=$(curl -s -X POST "${DEFECTDOJO_URL}/api/v2/product_types/" \
              -H "Authorization: Token ${DEFECTDOJO_API_KEY}" \
              -H "Content-Type: application/json" \
              -d "{\"name\": \"${ORG_NAME}\"}")

            if ! echo "$CREATE_RESPONSE" | jq empty > /dev/null 2>&1; then
              echo "Error: Failed to create product type. Response:"
              echo "$CREATE_RESPONSE"
              exit 1
            fi

            PRODUCT_TYPE_ID=$(echo "$CREATE_RESPONSE" | jq -r '.id')

            if [ -z "$PRODUCT_TYPE_ID" ]; then
              echo "Error: Could not extract product type ID. Response:"
              echo "$CREATE_RESPONSE"
              exit 1
            else
              echo "Product type '${ORG_NAME}' created successfully with ID: $PRODUCT_TYPE_ID"
            fi
          else
            echo "Product type '${ORG_NAME}' already exists with ID: $PRODUCT_TYPE_ID"
          fi
