name: Semgrep Scan and Upload to DefectDojo

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:1.78.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: | 
          semgrep \
            --json \
            --output semgrep-results.json \
            --metrics=off \
            --config="p/default"

      - name: Save raw report
        uses: actions/upload-artifact@v4
        with:
          name: raw_report
          path: semgrep-results.json

      - name: Check and Create Product in DefectDojo
        env:
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          ORG_NAME: "SemmmmmTest" # Название "организации" (продукта)
        run: |
          echo "Checking if product type 'Custom Type' exists in DefectDojo..."

          # Шаг 1: Проверка Product Type
          CUSTOM_TYPE_ID=$(curl -s -X GET "${DEFECTDOJO_URL}/api/v2/product_types/" \
            -H "Authorization: Token ${DEFECTDOJO_API_KEY}" \
            | jq -r --arg NAME "Custom Type" '.results[] | select(.name == $NAME) | .id')

          if [ -z "$CUSTOM_TYPE_ID" ]; then
            echo "Product type 'Custom Type' does not exist. Creating it..."

            CREATE_TYPE_RESPONSE=$(curl -s -X POST "${DEFECTDOJO_URL}/api/v2/product_types/" \
              -H "Authorization: Token ${DEFECTDOJO_API_KEY}" \
              -H "Content-Type: application/json" \
              -d '{"name": "Custom Type"}')

            CUSTOM_TYPE_ID=$(echo "$CREATE_TYPE_RESPONSE" | jq -r '.id')

            if [ -z "$CUSTOM_TYPE_ID" ]; then
              echo "Error: Failed to create 'Custom Type'. Response:"
              echo "$CREATE_TYPE_RESPONSE"
              exit 1
            fi

            echo "Product type 'Custom Type' created successfully with ID: $CUSTOM_TYPE_ID"
          else
            echo "Product type 'Custom Type' already exists with ID: $CUSTOM_TYPE_ID"
          fi

          # Шаг 2: Проверка продукта
          echo "Checking if product '${ORG_NAME}' exists in DefectDojo..."

          PRODUCT_ID=$(curl -s -X GET "${DEFECTDOJO_URL}/api/v2/products/" \
            -H "Authorization: Token ${DEFECTDOJO_API_KEY}" \
            | jq -r --arg NAME "$ORG_NAME" '.results[] | select(.name == $NAME) | .id')

          if [ -z "$PRODUCT_ID" ]; then
            echo "Product '${ORG_NAME}' does not exist. Creating it..."

            CREATE_PRODUCT_RESPONSE=$(curl -s -X POST "${DEFECTDOJO_URL}/api/v2/products/" \
              -H "Authorization: Token ${DEFECTDOJO_API_KEY}" \
              -H "Content-Type: application/json" \
              -d "{\"name\": \"${ORG_NAME}\", \"prod_type\": $CUSTOM_TYPE_ID}")

            PRODUCT_ID=$(echo "$CREATE_PRODUCT_RESPONSE" | jq -r '.id')

            if [ -z "$PRODUCT_ID" ]; then
              echo "Error: Failed to create product '${ORG_NAME}'. Response:"
              echo "$CREATE_PRODUCT_RESPONSE"
              exit 1
            fi

            echo "Product '${ORG_NAME}' created successfully with ID: $PRODUCT_ID"
          else
            echo "Product '${ORG_NAME}' already exists with ID: $PRODUCT_ID"
          fi
