name: Semgrep Scan and Upload to DefectDojo

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  semgrep:
    name: Semgrep Scan and Upload
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Выполнение Semgrep и сохранение результатов в JSON
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@fcd5ab7459e8d91cb1777481980d1b18b4fc6735
        with:
          output: semgrep-results.json  # Результаты сохраняются в этот файл

      # Шаг 3: Отправка результатов в DefectDojo
      - name: Upload Semgrep Results to DefectDojo
        env:
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
        run: |
          if [ -f semgrep-results.json ]; then
            curl -X POST "${DEFECTDOJO_URL}/api/v2/import_scan_results/" \
            -H "Authorization: Token $DEFECTDOJO_API_KEY" \
            -H "Content-Type: multipart/form-data" \
            -F 'scan_type=Semgrep' \
            -F "file=@semgrep-results.json" \
            -F 'engagement=Semgrep' \
            -F 'minimum_severity=Info'
          else
            echo "Error: semgrep-results.json not found!"
            exit 1
          fi
