name: Semgrep Scan and Upload to DefectDojo

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:1.78.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: | 
          semgrep \
            --json \
            --output semgrep-results.json \
            --metrics=off \
            --config="p/default"

      - name: Save raw report
        uses: actions/upload-artifact@v4
        with:
          name: raw_report
          path: semgrep-results.json

      - name: Upload Semgrep Results to DefectDojo
        env:
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          PRODUCT_NAME="SemgaTest"

          # Check if product exists
          PRODUCT_ID=$(curl -s -X GET "${DEFECTDOJO_URL}/api/v2/products/?name=${PRODUCT_NAME}" \
            -H "Authorization: Token $DEFECTDOJO_API_KEY" | jq -r '.results[0].id')

          if [ "$PRODUCT_ID" == "null" ]; then
            # Create product if not exists
            PRODUCT_ID=$(curl -s -X POST "${DEFECTDOJO_URL}/api/v2/products/" \
              -H "Authorization: Token $DEFECTDOJO_API_KEY" \
              -H "Content-Type: application/json" \
              -d '{"name": "'"$PRODUCT_NAME"'"}' | jq -r '.id')
            echo "Product $PRODUCT_NAME created with ID $PRODUCT_ID"
          else
            echo "Product $PRODUCT_NAME already exists with ID $PRODUCT_ID"
          fi

          # Check if engagement exists
          ENGAGEMENT_ID=$(curl -s -X GET "${DEFECTDOJO_URL}/api/v2/engagements/?name=${REPO_NAME}" \
            -H "Authorization: Token $DEFECTDOJO_API_KEY" | jq -r '.results[0].id')

          if [ "$ENGAGEMENT_ID" == "null" ]; then
            # Create engagement if not exists
            ENGAGEMENT_ID=$(curl -s -X POST "${DEFECTDOJO_URL}/api/v2/engagements/" \
              -H "Authorization: Token $DEFECTDOJO_API_KEY" \
              -H "Content-Type: application/json" \
              -d '{
                "name": "'"$REPO_NAME"'",
                "product": "'"$PRODUCT_ID"'",
                "status": "In Progress",
                "engagement_type": "CI/CD"
              }' | jq -r '.id')
            echo "Engagement $REPO_NAME created with ID $ENGAGEMENT_ID"
          else
            echo "Engagement $REPO_NAME already exists with ID $ENGAGEMENT_ID"
          fi

          # Upload the scan results
          if [ -f semgrep-results.json ]; then
            curl -X POST "${DEFECTDOJO_URL}/api/v2/import-scan/" \
              -H "Authorization: Token $DEFECTDOJO_API_KEY" \
              -H "Content-Type: multipart/form-data" \
              -F 'scan_type=Semgrep JSON Report' \
              -F "file=@semgrep-results.json" \
              -F "engagement=$ENGAGEMENT_ID" \
              -F 'auto_reimport=True' \
              -F 'minimum_severity=Info'
          else
            echo "Error: semgrep-results.json not found!"
            exit 1
          fi
